Make cli program installable from go get + Update README
nii236/adjectiveadjectiveanimal pull request #3
Opened 2020-12-22 04:35 UTC by comomac

2020-12-22 12:26 UTC, nii236 requested changes

2020-12-22 12:26 UTC, nii236 commented on cmd/aaa/main.go
> +	var rNum bool
Please provide more descriptive variable names

2020-12-23 03:04 UTC, comomac commented on cmd/aaa/main.go
> +	var rNum bool
vola~, fully descriptive variable names

2020-12-23 04:55 UTC, nii236 approved these changes

2020-12-23 04:55 UTC, nii236 commented
Thanks @comomac

2020-12-23 04:55 UTC, merged